### ISSUE TITLE
errors when using a shared atom compile cache between machines

### ISSUE THREAD

**Issue by whaaaley** [ricardofbarros/linter-js-standard#176]
I share my Atom folder between multiple computers via Dropbox.
This linter plugin is the only new thing I've added since the error started happening.
Deleting the `compile-cache` folder and re-opening Atom fixes the issue until I switch computers.

I will add a screenshot of the error here the next time it appears.

**Comment by whaaaley** [comment]
Yeah, everything should be identical, I'll look into removing compile cache from syncing anyway. I'll post the error message here just incase the next time it pops up. However my first thought was maybe a local path was being set that maybe shouldn't be.

**Comment by sonicdoe** [comment]
Feel free to post a screenshot of the error the next time it happens (I’m interested in what exactly goes wrong), however, I’ll close this for now since `compile-cache` (among other directories) shouldn’t really be synced across devices (see also the [`.gitignore` in `~/.atom`](https://github.com/atom/atom/blob/v1.18.0/dot-atom/.gitignore)).
