### ISSUE TITLE
[Linter] Invalid Linter Result received

### ISSUE THREAD

**Issue by lukasoppermann** [ricardofbarros/linter-js-standard#180]
Hey I am getting this error:

> **Something bad happened**
> astUtils.createGlobalLinebreakMatcher is not a function
> Referenced from: /Users/lukasoppermann/Code/veare/node_modules/standard/eslintrc.json

as well as 

> **[Linter] Invalid Linter Result received**
> These issues were encountered while processing messages from a linter named 'js-standard'
>  • Linter Result must be an Array

I've got `standard 10.0.2` installed in my repo and `linter-js-standard@3.9.0`.
Any idea why this happens? It happens every time I save the file or write anything (so whenever the linter runs).

Thanks.

**Comment by sonicdoe** [comment]
Does this also happen when running standard from the command line? Also, could you post the output of `npm ls eslint`?

**Comment by lukasoppermann** [comment]
It seems to have been fixed with the latest update.

**Comment by Arcanemagus** [comment]
@sonicdoe This is still possible.

The problem looks to be that if there was an error thrown in a `lintPromise`, `undefined` will be returned as the [`.catch()` block](https://github.com/ricardofbarros/linter-js-standard/blob/v3.9.3/lib/linter-js-standard.js#L91-L96) has no return statement.

I'd recommend returning `null` so that `linter` will simply keep it's current cache of messages for the provider (if it has any).

**Comment by sonicdoe** [comment]
@Arcanemagus Thanks 👍 Fixed in https://github.com/ricardofbarros/linter-js-standard/commit/32e8b7507b53eb56abc71e999892de813dd560c2.
