### ISSUE TITLE
Standard version is outdated

### ISSUE THREAD

**Issue by lukasoppermann** [ricardofbarros/linter-js-standard#183]
Does this package use the version it ships with, or the version from my deps? If it uses its own, it is at 8.6 but standard is at 10 already.

**Comment by ricardofbarros** [comment]
It uses the version from your deps if it finds one, if not it uses the standard that it's shipped with. That being said maybe I should update the standard.

**Comment by lukasoppermann** [comment]
I habe the issue that the plugin in atom complains about the extra padding, which was disabled in standard because it treats comments as padding. However running it through standard with gulp via cli does not bring up the "style error".

**Comment by ricardofbarros** [comment]
So it's using the `standard` from this package? I assume you don't have `standard` installed on the project of that file.

**Comment by lukasoppermann** [comment]
No, I do have standard in my dependencies and installed. I just figured it uses the standard from this package. Let me verify this though.

**Comment by sonicdoe** [comment]
standard will be updated in the next major version, see https://github.com/ricardofbarros/linter-js-standard/commit/53ede59e34ab8223404ca8c95bd4568bc3c0ccc8.

> However running it through standard with gulp via cli does not bring up the "style error".

@lukasoppermann It sounds like you depend on `gulp-standard` instead of `standard` itself. If that’s the case, you might be interested in https://github.com/ricardofbarros/linter-js-standard/issues/178.
