### ISSUE TITLE
Linter doesn't seem to be receiving options from package.json

### ISSUE THREAD

**Issue by saadq** [ricardofbarros/linter-js-standard#206]
For example, let's say I have this in my `package.json` file:

```json
{
  "standard": {
    "ignore": ["src/tests"]
  }
}
```

If I run `standard` in the command line, I don't get any errors. However, when I open the file in my editor, I still have the errors displayed:

![screen shot 2017-09-12 at 4 51 48 pm](https://user-images.githubusercontent.com/5678694/30347617-b28b4814-97da-11e7-982d-a77615958ff3.png)

I'm on Atom v1.20.0 and using `linter-js-standard` v4.0.1. Let me know if I can provide any other info.

**Comment by sonicdoe** [comment]
Thank you, I was able to reproduce this.

The issue is that [minimatch](https://github.com/isaacs/minimatch) doesn’t match directories (like e.g. `.gitignore` does). Coincidentally, [ESLint had the same issue](https://github.com/eslint/eslint/issues/1069) three years ago. I’ll probably fix this using [ignore](https://github.com/kaelzhang/node-ignore) in the next patch version.

**Comment by sonicdoe** [comment]
Should be fixed in v4.0.2.
